---
title: "Tfoster_Review"
author: "Tyler Foster"
date: "3/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

####################################################################################################################

Initial feedback:
There were absolutely no errors when running the code. You did have a message, "NAs introduced by coercion" when using as.numeric. However, that's totally fine as there are missing/multiple values that can't be changed to numeric values. You did a great job analyzing each of the files! I really liked your graph that had a side-by-side comparison of teosinte and maize SNP positions - I definitely need to modify my code to include something similar! Great usage of having R print the files in their own directories! Your "on your own" visualization was so creative!

Suggestions:
1. Separate reading in a file (such as fang et al file) from the main chunk where you do your data inspection. When trying to run that chunk, it took 5 minutes to run. The SNP file did not have this issue as it's much smaller.
2. The SNP Distribution is a visually pleasing graph! However, why not use a geom_point graph instead? Geom_point would give you a better idea of gap regions that you have across each chromosome - in your figure, chromosome 7 is the only chromosome with a gap region. 
  *As I know from your review of my code, you prefer using the histograms for this visualization. Just know, you cannot see gap regions*


Overall, all of your graphs are visually satisfying. I can tell that a lot of time was spent thinking, planning, organizing, and coding your thoughts! Fantastic work!!

####################################################################################################################